### ISSUE TITLE
SublimeLinter-contrib-ansible-lint isn't in PackageControl

### ISSUE THREAD

**Issue by nklmilojevic** [mliljedahl/SublimeLinter-contrib-ansible-lint#1]
Hi, 

I don't know if I missed something - but I cannot find SublimeLinter-contrib-ansible-lint in Package Control. Is this a known issue?

**Comment by mliljedahl** [comment]
@nklmilojevic Thanks to your comment on the ticket in the SublimeLinter repo this plugin is now on it's way to Package Control. Let me know if there is any problems with it or if you have suggestions for improvements.

**Comment by nklmilojevic** [comment]
Woohoo, great, thanks a lot. Package is now in Package Control so I'll be closing this issue.
