### ISSUE TITLE
Linter not working

### ISSUE THREAD

**Issue by ghost** [mliljedahl/SublimeLinter-contrib-ansible-lint#4]
ansible-lint on terminal gives me these errors for the yml file 

⇒  ansible-lint sublime-plugin-install.yml
[ANSIBLE0012] Commands should not change things if nothing needs doing
sublime-plugin-install.yml:6
Task/Handler: Find out playbook's path

[ANSIBLE0013] Use shell only when shell functionality is required
sublime-plugin-install.yml:6
Task/Handler: Find out playbook's path

[ANSIBLE0012] Commands should not change things if nothing needs doing
sublime-plugin-install.yml:10
Task/Handler: Detecting Sublime Text folder details

However the plugin shows no messages in console (opened using ctrl + tild ).

This is the Settings file 

`{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "ansiblelint": {
                "@disable": false,
                "R": "",
                "args": [],
                "exclude": "",
                "excludes": [],
                "r": "",
                "t": "",
                "x": ""
            }
        },
        "mark_style": "fill",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "coffeescript (gulpfile)": "coffeescript",
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "javascript (eslint)": "javascript",
            "javascript (gruntfile)": "javascript",
            "javascript (gulpfile)": "javascript",
            "javascript (postcss)": "javascript",
            "javascript (stylelint)": "javascript",
            "javascript (webpack)": "javascript",
            "json (babel)": "json",
            "json (bower)": "json",
            "json (composer)": "json",
            "json (eslint)": "json",
            "json (npm)": "json",
            "json (postcss)": "json",
            "json (settings)": "json",
            "json (stylelint)": "json",
            "json (sublime)": "json",
            "json (tern js)": "json",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python",
            "xml (config)": "xml",
            "xml (svg)": "xml",
            "yaml (circleci)": "yaml",
            "yaml (docker)": "yaml",
            "yaml (eslint)": "yaml",
            "yaml (lock)": "yaml",
            "yaml (procfile)": "yaml",
            "yaml (stylelint)": "yaml",
            "yaml (yarn)": "yaml"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
`
I have attached the screenshot depicting the syntax read as YAML.

![screen shot 2017-10-31 at 7 14 18 am](https://user-images.githubusercontent.com/23047702/32228325-314859ca-be0b-11e7-814d-164eecfd9909.png)

Pressed alt + command + P ..and selected SublimeLinter:Show all errors.

Attaching the screenshot of the same

![screen shot 2017-10-31 at 7 16 24 am](https://user-images.githubusercontent.com/23047702/32228489-a02bc980-be0b-11e7-8bf5-73065410d520.png)

The status bar at the bottom shows no lint errors.

![screen shot 2017-10-31 at 7 19 47 am](https://user-images.githubusercontent.com/23047702/32228601-ec1bce08-be0b-11e7-95e6-57b64f44c0c8.png)

**Comment by ghost** [comment]
@mliljedahl or @pymag09 ...can anyone of you help me with this.

**Comment by pymag09** [comment]
Hello @harshit22394 
First of all please set `Tools`->`SublimeLinter`->`Lint Mode`->`Load/save`
`All Errors` doesn't work for me as well.
Second. It works only for playbooks not for roles.
Open console, open any playbook, you have to see someting like this:

> SublimeLinter: ansiblelint: your_PLAYBOOK_HERE ['/usr/local/bin/ansible-lint', '-p', '--nocolor', '@'] 

It will appear only if you have fixed `tempfile_suffix = 'yml'`
This is how it works in my case.

**Comment by pymag09** [comment]
@harshit22394 And you have not configured `Apply Syntax` plugin. Must Ansible instead f YAML

**Comment by ghost** [comment]
hi @pymag09 .. i have done the tempfile_suffix fix (made changes in linter.py) also set the Lint mode to Load/Save.....However now i am getting this error

SublimeLinter: WARNING: ansiblelint deactivated, cannot locate 'ansible-lint' 

where as $PATH contains the path to ansible-lint

HarshitSinghvi@harshit:~/Desktop|⇒  echo $PATH
/Users/HarshitSinghvi/bin:/Users/HarshitSinghvi/Library/Python/2.7/bin/ansible-lint:/Users/HarshitSinghvi/bin

**Comment by ghost** [comment]
And also it is configure to Ansible ...Have selected Ansible from the drop down list after selecting YAML from the bottom bar

**Comment by ghost** [comment]
Details in the console:

SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/HarshitSinghvi/Downloads/infraredscripts-develop@a1964c82443/bin
/Users/HarshitSinghvi/Downloads/infraredscripts-develop@a1964c82443/bin
 
SublimeLinter: WARNING: ansiblelint deactivated, cannot locate 'ansible-lint'

**Comment by ghost** [comment]
@pymag09 

SublimeLinter: ansiblelint: your_PLAYBOOK_HERE ['/usr/local/bin/ansible-lint', '-p', '--nocolor', '@']

I am not seeing this line in console though even after doing the tempfile_suffix fix

**Comment by pymag09** [comment]
@harshit22394 Have you installed ansible-lint? `which ansible-lint`
Try to put absolute path in cmd = '**/usr/local/bin/ansible-lint** -p --nocolor @'

**Comment by ghost** [comment]
Set this to 

  cmd = ('/Users/HarshitSinghvi/Library/Python/2.7/bin/ansible-lint', '-p', '--nocolor', '@')

Can you tell me how to initiate the Lint

**Comment by pymag09** [comment]
It will be initiated when you open or save playbook. Automatically

**Comment by ghost** [comment]
Got the output
@pymag09

SublimeLinter: ansiblelint output:
/Users/HarshitSinghvi/workspace/iag/macsetup/ansible/playbooks/sublime-plugin-install.yml:6: [EANSIBLE0012] Commands should not change things if nothing needs doing
/Users/HarshitSinghvi/workspace/iag/macsetup/ansible/playbooks/sublime-plugin-install.yml:6: [EANSIBLE0013] Use shell only when shell functionality is required
/Users/HarshitSinghvi/workspace/iag/macsetup/ansible/playbooks/sublime-plugin-install.yml:10: [EANSIBLE0012] Commands should not change things if nothing needs doing 


thank you so much...

**Comment by ghost** [comment]
any idea why it is not picking the path @pymag09

HarshitSinghvi@harshit:~|⇒  which ansible-lint
/Users/HarshitSinghvi/Library/Python/2.7/bin/ansible-lint

**Comment by ghost** [comment]
working perfect now @pymag09 ...actually the path was not set in bash_profile since i am a tcsh user ....adding the path in ~/.bash_profile solved the issue...once again thnks fr ur help ..reallyappreciate it.

**Comment by pymag09** [comment]
No idea :) So far I am happy with what I have. However I don;t have any problem with which ansible-lint. For example form time to time I have problems with `IndexError: list index out of range`. I see this error in console along with linter output. But it is better compared to what Atom can offer :)
